version: "3.9"
services:
  discovery:
    image: consul:1.15
    ports:
      - 8500:8500

  serveur-conf:
    image: ghcr.io/laurich-app/serveur-conf:latest

  postgres-utilisateur:
    image: postgres:12.17
    environment:
      - POSTGRES_DB=service-utilisateur
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pswd

  service-utilisateur:
    image: ghcr.io/laurich-app/service-utilisateur:latest
    container_name: service-utilisateur
    environment:
      - URL_CONFIG_SERVEUR=http://serveur-conf:8888
      - CONSUL_HOST=discovery
      - CONSUL_PORT=8500
      - PRIVATE_KEY=app_pkcs8.prv
      - PUBLIC_KEY=app.pub
      - POSTGRES_URL=jdbc:postgresql://postgres-utilisateur:5432/service-utilisateur
      - POSTGRES_USER=user
      - POSTGRES_PSWD=pswd
      - RABBIT_HOST=rabbit
    depends_on:
      - serveur-conf
      - discovery
      - postgres-utilisateur
      - rabbit
    restart: always

  mongo-commande:
    image: mongo:7.0.5
    environment:
      - MONGO_INITDB_DATABASE=service-commande
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pswd

  service-commande:
    image: ghcr.io/laurich-app/service-commandes:latest
    environment:
      - URL_CONFIG_SERVEUR=http://serveur-conf:8888
      - CONSUL_HOST=discovery
      - CONSUL_PORT=8500
      - MONGO_URL=mongodb://user:pswd@mongo-commande:27017/
      - MONGO_DATABASE=commande
      - RABBIT_HOST=rabbit
    depends_on:
      - serveur-conf
      - discovery
      - mongo-commande
      - rabbit
    restart: always

  postgres-produits:
    image: postgres:12.17
    environment:
      - POSTGRES_DB=service-produits
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pswd

  service-produits:
    image: ghcr.io/laurich-app/service-produits:latest
    environment:
      - URL_CONFIG_SERVEUR=http://serveur-conf:8888
      - CONSUL_HOST=discovery
      - CONSUL_PORT=8500
      - POSTGRES_URL=jdbc:postgresql://postgres-produits:5432/service-produits
      - POSTGRES_USER=user
      - POSTGRES_PSWD=pswd
      - RABBIT_HOST=rabbit
    depends_on:
      - serveur-conf
      - discovery
      - postgres-produits
      - rabbit
    restart: always

  service-notification:
    image: ghcr.io/laurich-app/service-notification:latest
    environment:
      - URL_CONFIG_SERVEUR=http://serveur-conf:8888
      - CONSUL_HOST=discovery
      - CONSUL_PORT=8500
    depends_on:
      - serveur-conf
      - discovery
      - rabbit
    restart: always

  service-reapprovisionnement:
    container_name: service-reappro
    image: ghcr.io/laurich-app/service-reapprovisionnement:latest
    environment:
      - CONSUL_HOST=discovery
      - CONSUL_PORT=8500
      - MONGO_URL=mongodb://user:pswd@mongo-reappro:27017/
      - MONGO_DATABASE=reappro
      - RABBIT_HOST=rabbit
    depends_on:
      - discovery
      - mongo-reappro
      - rabbit
    restart: always

  mongo-reappro:
    image: mongo:7.0.5
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pswd

  client:
    image: ghcr.io/laurich-app/client:latest

  service-passerelle:
    image: ghcr.io/laurich-app/service-passerelle:latest
    ports:
      - 8080:8080
    environment:
      - CLIENT_URL=http://client
      - CONSUL_HOST=discovery
      - CONSUL_PORT=8500

  rabbit:
    image: rabbitmq:3.12.13-management
